
    export default [
        {
          id: 1,
          img: "excalibur-background1.jpg",
          alt: 'official trailer',
          title: 'Official Trailer',
          backImg: "excalibur-background1.jpg",
          vidSrc: "6QR6_17mn5s?rel=0",
        },
        {
            id: 2,
            img: 'excalibur-background2.jpeg',
            alt: 'official trailer 2',
            title: 'Official Trailer 2',
            backImg: 'excalibur-background2.jpeg',
            vidSrc: "WCoqdyjVnkk?rel=0?rel=0",
          },
          {
            id: 3,
            img: 'excalibur-background3.jpg',
            alt: 'the lady of the lake',
            title: 'The Lady of the Lake',
            backImg: 'excalibur-background3.jpg',
            vidSrc: "2C8fB8p6crY?rel=0",
          },
          {
            id: 4,
            img: 'excalibur-background4.png',
            alt: 'The Knights of the Round Table',
            title: 'The Knights of the Round Table',
            backImg: 'excalibur-background4.png',
            vidSrc: "H2hbov4Rb6g?rel=0",
          },
          {
            id: 5,
            img: 'excalibur-background5.png',
            alt: 'Where Hides Evil?',
            title: 'Where Hides Evil?',
            backImg: 'excalibur-background5.png',
            vidSrc: "J-fa9awvFBY?rel=0",
          },
          {
            id: 6,
            img: 'excalibur-background6.png',
            alt: 'Wedding Knight',
            title: 'Wedding Knight',
            backImg: 'excalibur-background6.png',
            vidSrc: "4gO9OFumO8U?rel=0",
          },
      ];
